---
title: "Growth model analysis"
output: html_notebook
---

```{r functions}
theme_publication <- function(base_size=14, base_family="") {
  library(grid)
  library(ggthemes)
  (theme_foundation(base_size=base_size, base_family=base_family)
    + theme(plot.title = element_text(face = "bold",
                                      size = rel(1.2), hjust = 0.5),
            text = element_text(),
            panel.background = element_rect(colour = NA),
            plot.background = element_rect(colour = NA),
            axis.title = element_text(face = "bold",size = rel(1)),
            axis.title.y = element_text(angle=90,vjust =2),
            axis.title.x = element_text(vjust = -0.2),
            axis.text = element_text(),
            axis.line = element_line(colour="black"),
            axis.ticks = element_line(),
            panel.grid.major = element_line(colour="#f0f0f0"),
            panel.grid.minor = element_blank(),
            legend.key = element_rect(colour = NA),
            legend.position = "bottom",
            legend.direction = "horizontal",
            legend.key.size= unit(0.2, "cm"),
            legend.margin = unit(0, "cm"),
            legend.title = element_text(face="italic"),
            plot.margin=unit(c(10,5,5,5),"mm"),
            strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
            strip.text = element_text(face="bold"),
            panel.border = element_rect(colour = "black")
    ))

}

scale_fill_Publication <- function(...){
  library(scales)
  discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
  library(scales)
  discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

```


Plots for the manuscript

```{r message=FALSE}
library(arrayhelpers)
library(tidyverse)

load("D:/projects/linkedModels/data/out/ddD_bktbntats_1997.RData")
load("D:/projects/linkedModels/data/out/countsAndMasses.RData")

mcmc <- list()
load("D:/projects/linkedModels/data/out/dG_1518555667_bkt1997_Nimble.RData")

# input data
d1 <- ddG[[1]][[1]]
d2 <- ddG[[1]][[2]]
meanSampleIntervalMean <- data.frame( meanSampleInterval = colMeans(d1$sampleIntervalMean), season = 1:d1$nSeasons )

#RECALCULATE gr for dataset. Filtering by maxSampleInterval in the creat ddddG step leaves in trailing lengths from the long samp intervals
d2 <- d2 %>%
  group_by(tag) %>%
  # arrange(tag,sampleNumber) %>%
  mutate( lagObservedWeight = lead(observedWeight),
          lagObservedLength = lead(observedLength),
          grWeight = exp(lagObservedWeight - observedWeight)/as.numeric((lagDetectionDate - detectionDate)),
          grLength = (lagObservedLength - observedLength)/as.numeric((lagDetectionDate - detectionDate))
  )  
#d2 %>% filter(tag=='00088cc059') %>% select(tag,riverOrdered,riverN,lagRiverN,sampleNumber,observedLength,lagObservedLength)



# output data
mcmc[['bkt']] <- mcmcProcessed


load("D:/projects/linkedModels/data/out/dG_1518559325_bnt1997_Nimble.RData")
mcmc[['bnt']]  <- mcmcProcessed

load("D:/projects/linkedModels/data/out/dG_1518559991_ats1997_Nimble.RData")
mcmc[['ats']]  <- mcmcProcessed

rm(ddG,dG,mcmcProcessed)

load("D:/projects/linkedModels/data/cd_west_1997.RData")
```

```{r raw counts}
allFishBySpecies$riverOrderedGG <- factor(allFishBySpecies$river,
                         levels=c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),
                         labels = c("West Brook","Open Large","Open Small","Isolated Small"), ordered = T)
allFishBySpecies$seasonGG <- factor(allFishBySpecies$season, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
allFishBySpecies$speciesGG <- factor(allFishBySpecies$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)

allFish$riverOrderedGG <- factor(allFish$river,
                         levels=c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),
                         labels = c("West Brook","Open Large","Open Small","Isolated Small"), ordered = T)
allFish$seasonGG <- factor(allFish$season, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)

ggplot(allFishBySpecies, aes(year,nAllFishBySpecies)) +
  geom_point(aes(color = speciesGG)) +
  geom_line(aes(color = speciesGG)) +
  geom_line( data = allFish, aes(year,nAllFish) ) +
  theme_publication() +
  labs( x = "Year", y = "Count" ) +
  facet_grid( seasonGG ~ riverOrderedGG)#, scales = "free_y" )

ggsave('figures/rawCount.png')

tmp <- d %>% distinct(season,year,sampleNumber)
allFishBySpecies <- left_join(allFishBySpecies,tmp)
allFish <- left_join(allFish,tmp)

ggplot(allFishBySpecies, aes(sampleNumber,nAllFishBySpecies)) +
  geom_point(aes(color = speciesGG)) +
  geom_line(aes(color = speciesGG)) +
  geom_line( data = allFish, aes(sampleNumber,nAllFish) ) +
  theme_publication() +
  labs( x = "SampleNumber", y = "Count" ) +
  facet_wrap(  ~riverOrderedGG )#, scales = "free_y" )


```


```{r p(detection)}
  # ggPInt <- array2df(ddD$sims.list$pBetaInt, label.x = "est")
  # 
  # ggPInt$chain <- rep(1:ddD$mcmc.info$n.chains, each = ddD$mcmc.info$n.samples/ddD$mcmc.info$n.chains)
  # ggPInt$iter <- 1:as.numeric(ddD$mcmc.info$n.samples/ddD$mcmc.info$n.chains)
  # 
  # ggplot(filter(ggPInt), aes(iter,est)) + 
  #   geom_point( aes(color=factor(chain)), size = 0.1 ) + 
  #   ylim(-1.5,1.5) + 
  #   facet_grid(d2+d4~d5+d3)

  p <- array2df(ddD$q50$pBetaInt, label.x = "est") %>%
    rename(est=est,species=d1,season=d2,river=d3,year=d4)
  ggplot(p, aes(year,invlogit(est))) +geom_point() + facet_grid(season ~ river + species)
 
   ggsave('figures/p.png')
  
  phi <- array2df(ddD$q50$phiBetaInt, label.x = "est") %>%
    rename(est=est,species=d1,season=d2,river=d3,year=d4)
  ggplot(phi, aes(year,invlogit(est))) +geom_point() + facet_grid(season ~ river + species)

# # of skunked sections    
  tmp <- dddD[[2]] %>%
           group_by(riverOrdered,year,season,section) %>%
           summarize( s = sum(enc) ) %>%
           filter( s == 0 )
  table(tmp$riverOrdered,tmp$year,tmp$season)
  
```


```{r overview graphs - Fig 1}
d$riverOrderedGG <- factor(d$river,
                         levels=c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),
                         labels = c("West Brook","Open Large","Open Small","Isolated Small"), ordered = T)
d$seasonGG <- factor(d$season, labels = c("Spring","Summer","Autumn","Winter"), ordered = T)
d$speciesGG <- factor(d$species, levels = c('bkt','bnt','ats'), labels = c("Brook Trout", "Brown Trout", "Atlantic Salmon"), ordered = T)


ggplot(d, aes(year,nAllFishBySpeciesP)) +
  geom_point(aes(color=speciesGG)) +
  geom_line(aes(color=speciesGG)) +
  labs( x = "Year", y = "Estimated count") +
#  ylim(0,2500) +
  theme_publication() +
  facet_grid(seasonGG ~ riverOrderedGG, scales = "free")

ggsave('figures/count.png')

ggplot(d, aes(year,nAllFishBySpeciesP)) +
  geom_point(aes(color=species)) +
  geom_line(aes(color=species)) +
   geom_line(  aes(year,nAllFishP) ) +
  labs( x = "Year", y = "Estimated count") +
#  ylim(0,2500) +
  theme_publication() +
  facet_grid(seasonGG ~ riverOrderedGG, scales = "free")
```
```{r raw growth rates}

cdMeans <- cd %>%
  mutate( gr = (observedLength - lagObservedLength)/as.integer(detectionDate - lagDetectionDate) ) %>%
  group_by(species,riverOrdered,season) %>%
  summarize( meanGr = mean( gr, na.rm = TRUE ),
             sdGr = sd( gr, na.rm = TRUE )) %>%
  mutate( meanGrUp = meanGr + sdGr,
          meanGrDn = meanGr - sdGr
          )

pd <- position_dodge(0.05) # move them .05 to the left and right

# all three species
ggplot( cdMeans %>% filter(riverOrdered == 'west brook'), aes(season, meanGr, color = species) ) +
  geom_errorbar(aes(ymin = meanGrDn, ymax = meanGrUp), width = 0.25, position = pd) +
  geom_point( size = 2 ) +
  geom_line()

cd$isYOY <- ifelse( cd$ageInSamples <= 3, 1, 2 )
cdMeansByisYOY <- cd %>%
  mutate( gr = (observedLength - lagObservedLength)/as.integer(detectionDate - lagDetectionDate) ) %>%
  group_by(species,riverOrdered,season,isYOY) %>%
  summarize( meanGr = mean( gr, na.rm = TRUE ),
             sdGr = sd( gr, na.rm = TRUE )) %>%
  mutate( meanGrUp = meanGr + sdGr,
          meanGrDn = meanGr - sdGr
          )

# all three species
ggplot( cdMeansByisYOY %>% filter(riverOrdered == 'west brook', !(season == 2 & isYOY == 1)), aes(season, meanGr, color = species) ) +
  geom_errorbar(aes(ymin = meanGrDn, ymax = meanGrUp), width = 0.25, position = pd) +
  geom_point( size = 2 ) +
  geom_line()+
  facet_wrap(~isYOY)

# all three species by river
ggplot( cdMeansByisYOY %>% filter(!(season == 2 & isYOY == 1)) , aes(season, meanGr, color = riverOrdered) ) +
  geom_errorbar(aes(ymin = meanGrDn, ymax = meanGrUp), width = 0.25, position = pd) +
  geom_point( size = 2 ) +
  geom_line()+
  facet_grid(species~isYOY)

# bkt only
pdBKT <- position_dodge(0.05) # move them .05 to the left and right
ggplot( cdMeans %>% filter(species=='bkt'), aes(season, meanGr, color = riverOrdered) ) +
  geom_errorbar(aes(ymin = meanGrDn, ymax = meanGrUp), width = 0.25, position = pdBKT) +
  geom_point( size = 3 ) +
  geom_line( size = 1 ) +
  facet_wrap(~isYOY)

```
```{r growth by movement}
d2$isYOY <- ifelse( d2$ageInSamples <= 3, 1, 2 )
d2 <-  d2 %>%
  group_by(tag) %>%
  mutate( lagRiverN = lead(riverN), 
          riverNMove = paste(riverN,lagRiverN, sep="_")
          #gr = (observedLength - lagObservedLength)/as.integer(detectionDate - lagDetectionDate)
          )

#d2 %>% filter(tag=='00088cbf44') %>% select(tag,riverN,lagRiverN,sampleNumber,observedLength,lagObservedLength)
table(d2$riverNMove)

cdMeansByisYOYriverNMove <- d2 %>%
  #mutate( gr = (observedLength - lagObservedLength)/as.integer(detectionDate - lagDetectionDate) ) %>%
  group_by(species,riverN,lagRiverN,season,isYOY) %>%
  summarize( meanGr = mean( grLength, na.rm = TRUE ),
             sdGr = sd( grLength, na.rm = TRUE ),
             n = n()) %>%
  mutate( meanGrUp = meanGr + sdGr,
          meanGrDn = meanGr - sdGr
          )

# 
ggplot( cdMeansByisYOYriverNMove %>% filter(!(season == 2 & isYOY == 1), species == "bkt", isYOY == 2) , aes(season, meanGr, color = factor(lagRiverN)) ) +
  geom_errorbar(aes(ymin = meanGrDn, ymax = meanGrUp), width = 0.25, position = pd) +
  geom_point( size = 2 ) +
  geom_line()+
  facet_wrap(~riverN)

d2 %>% filter(riverN == 1 & lagRiverN == 4) %>% select(tag,river,sampleNumber)
d2 %>% filter(riverN == 2, is.na(lagRiverN), !is.na(grLength)) %>% select(tag,riverN,sampleNumber,lagRiverN,observedLength,lagObservedLength,gr,grLength)
d2 %>% filter(tag=='00088cc059') %>% select(tag,riverOrdered,riverN,lagRiverN,sampleNumber,observedLength,lagObservedLength,gr,grLength)
```



```{r figs 3,4}
d %>% group_by(riverOrderedGG,seasonGG,year) %>%
  filter( riverOrderedGG == "West Brook" ) %>%
  summarize(meanF = mean(meanFlow, na.rm=T),
            sdF = sd(meanFlow, na.rm=T)) %>%
  ggplot( aes(year,meanF) ) +
  geom_point( size = 3 ) +
  geom_line() +
 # geom_smooth(method = 'lm', se=F) +
  geom_errorbar( aes(ymin = meanF - sdF, ymax = meanF + sdF, width = 0.33 ) ) +
  labs( x = "Year", y = "Stream flow (x/x)" ) +
  theme_publication() +
  facet_wrap(~seasonGG)

ggsave('figures/flow.png')

lmFunction <- function(df){ lm( meanT ~ year, data=df ) }

tempMods <- d %>%
  group_by(riverOrderedGG,seasonGG,year) %>%
  summarize(meanT = mean(meanTemperature, na.rm=T),
            sdT = sd(meanTemperature, na.rm=T)) %>%
  group_by( riverOrderedGG, seasonGG ) %>%
  nest() %>%
  mutate( model = map(data,lmFunction) )

tempModsTidy <- tempMods %>%
  mutate(tidy = map(model,broom::tidy)) %>%
  select(-data,-model) %>%
  unnest() %>%
  filter( term == 'year') %>%
  mutate( sig = ifelse(p.value < 0.05,"*",""))

d %>% group_by(riverOrderedGG,seasonGG,year) %>%
  summarize(meanT = mean(meanTemperature, na.rm=T),
            sdT = sd(meanTemperature, na.rm=T)) %>%
  ggplot( aes(year,meanT) ) +
  geom_smooth(method = 'lm', se=F, color = 'darkgrey') +
  geom_point(  ) +
  geom_line() +
  geom_errorbar( aes(ymin = meanT - sdT, ymax = meanT + sdT, width = 0.33 ) ) +
  labs( x = "Year", y = "Stream temperature (C)" ) +
  geom_text(data=tempModsTidy,aes(x=1999,y=18, label=paste(round(estimate,2),sig))) +
  theme_publication() +
  facet_grid(seasonGG ~ riverOrderedGG)


ggsave('figures/temp.png')
```

```{r questions}




```

```{r mcmc output analysis}

riverOrderedIn <- factor(c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),levels=c('west brook', 'wb jimmy', 'wb mitchell',"wb obear"),labels = c("west brook","wb jimmy","wb mitchell","wb obear"), ordered = T)

grInt <- list()
grInt[['bkt']] <- array2df(mcmc[['bkt']]$sims.list$grInt, levels = list(iter=NA,isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:4]), label.x="int")
grInt[['bnt']] <- array2df(mcmc[['bnt']]$sims.list$grInt, levels = list(iter=NA,isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:2]), label.x="int")
grInt[['ats']] <- array2df(mcmc[['ats']]$sims.list$grInt, levels = list(iter=NA,isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:1]), label.x="int")


ggplot( grInt[['bkt']] %>% filter(river %in% c('west brook','wb jimmy')), aes(exp(int))) +
  geom_freqpoly() +
  geom_freqpoly(aes(exp(int)),color = 'brown', data = grInt[['bnt']]) +
  geom_freqpoly(aes(exp(int)),color = 'lightblue', data = grInt[['ats']]) +
 # xlim(-0.5,1.5) +
  theme_publication() +
  facet_grid(season ~ river + isYOY)

# as range plot
probs <- c(0.05,0.1,0.5,0.9,0.95)
q <- grInt[['bkt']] %>%
  group_by(isYOY,season,river) %>%
  summarize(
    p = list(probs),
    q = list(quantile(int,probs))
  ) %>%
  unnest() %>%
  spread(key = p, value = q)


p <- array2df(mcmc[['bkt']]$mean$grInt, levels = list(isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:4]), label.x="int") %>%
  mutate( season = as.numeric(season) ) %>%
  left_join(.,meanSampleIntervalMean, by = 'season')
p$intByDay <- p$int/p$meanSampleInterval
p$intByDay <- ifelse(p$isYOY == 1 & p$season == 2, NA, p$intByDay)
p$parameter <- paste(p$river,p$season,sep="_")

pUp <- array2df(mcmc[['bkt']]$q97.5$grInt, levels = list(isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:4]), label.x="intUp") %>%
  mutate( season = as.numeric(season) ) 
pDown <- array2df(mcmc[['bkt']]$q2.5$grInt, levels = list(isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:4]), label.x="intDown") %>%
  mutate( season = as.numeric(season) )
p$intByDayUp <- p$intUp/p$meanSampleInterval; p$intByDayDown <- p$intDown/p$meanSampleInterval
p$intByDay <- ifelse(p$isYOY == 1 & p$season == 2, NA, p$intByDay)
p <- left_join(p,pUp) %>% left_join(.,pDown)

   ggplot(p, aes(x = intByDay, y = reorder(parameter,intByDay,na.rm=TRUE), color = factor(season), shape = factor(season))) + 
      geom_point(size = 3) +
      facet_grid(~isYOY)
     
      geom_segment(aes(x = Low, 
      xend = High, yend = reorder(Parameter, median)), 
      size = 1.5) + geom_segment(aes(x = low, xend = high, 
      yend = reorder(Parameter, median)), size = 0.5) + 
      xlab("HPD") + ylab("Parameter")

        
```

```{r}
        
sigmaInt <- list()
sigmaInt[['bkt']] <- array2df(mcmc[['bkt']]$sims.list$sigmaInt, levels = list(iter=NA,isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:4]), label.x="int")
sigmaInt[['bnt']] <- array2df(mcmc[['bnt']]$sims.list$sigmaInt, levels = list(iter=NA,isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:2]), label.x="int")
sigmaInt[['ats']] <- array2df(mcmc[['ats']]$sims.list$sigmaInt, levels = list(iter=NA,isYOY=c(0,1),season=1:4,river=riverOrderedIn[1:1]), label.x="int")

bw <- 0.05
ggplot( sigmaInt[['bkt']] %>% filter(river %in% c('west brook','wb jimmy')), aes(int)) +
  geom_freqpoly(binwidth = bw) +
  geom_freqpoly(aes(int),binwidth = bw,color = 'brown', data = sigmaInt[['bnt']]) +
  geom_freqpoly(aes(int),binwidth = bw,color = 'lightblue', data = sigmaInt[['ats']]) +
  #xlim(-4.5,-1) +
  xlim(-5,2.5) +
  theme_publication() +
  facet_grid(season ~ river + isYOY)

```

```{r ind RE among spp}

grIndRE <- list()
grIndRE[['bkt']] <- as.data.frame(mcmc[['bkt']]$q50$grIndRE); names(grIndRE[['bkt']]) <- 'value'
grIndRE[['bnt']] <- as.data.frame(mcmc[['bnt']]$q50$grIndRE); names(grIndRE[['bnt']]) <- 'value'
grIndRE[['ats']] <- as.data.frame(mcmc[['ats']]$q50$grIndRE); names(grIndRE[['ats']]) <- 'value'

ggplot( grIndRE[[1]], aes(value,..density..) ) +
  geom_freqpoly(binwidth = 0.0025) +
  geom_freqpoly(aes(value), color = "brown", binwidth = 0.0025, data = grIndRE[[2]]) +
  geom_freqpoly(aes(value), color = "lightblue", binwidth = 0.0025, data = grIndRE[[3]])

```

```{r tables}

round(mcmc$summary$all.chains[startsWith(attributes(mcmc$summary$all.chains)$dimnames[[1]], "grBeta["),],2)

```



```{r overview graphs - Fig Appendix}

pd <- position_dodge(0.65)

# isYOY1
d %>% group_by(speciesGG,riverOrderedGG,seasonGG,year) %>%
  filter(isYOYDATA == 1) %>%
  summarize(meanGR = mean(grLength, na.rm=T),
            sdGR = sd(grLength, na.rm=T)) %>%
ggplot( aes(year,meanGR, color=speciesGG, shape=speciesGG) ) +
  geom_point( position=pd ) +
  geom_errorbar( aes(ymin = meanGR - sdGR, ymax = meanGR + sdGR), width = 0.33, position=pd ) +
  ggtitle( "isYOY = 1" ) +
  labs( x = "Year", y = "Growth rate (mm/d)" ) +
  scale_x_continuous( breaks = 1997:2015 ) +
  theme_publication() +
  theme( panel.grid.minor = element_blank(),
         axis.text.x  = element_text(angle=90, vjust=0.5, size=8) ) +
  facet_grid(seasonGG ~ riverOrderedGG)

ggsave('figures/grByYearYOY1.png')

# isYOY2
d %>% group_by(speciesGG,riverOrderedGG,seasonGG,year) %>%
  filter(isYOYDATA == 2) %>%
  summarize(meanGR = mean(grLength, na.rm=T),
            sdGR = sd(grLength, na.rm=T)) %>%
  ggplot( aes(year,meanGR, color=speciesGG, shape=speciesGG) ) +
  geom_point( position=pd ) +
  geom_errorbar( aes(ymin = meanGR - sdGR, ymax = meanGR + sdGR), width = 0.33, position=pd ) +
  ggtitle( "isYOY = 2" ) +
  labs( x = "Year", y = "Growth rate (mm/d)" ) +
  scale_x_continuous( breaks = 1997:2015 ) +
  theme_publication() +
  theme( panel.grid.minor = element_blank(),
         axis.text.x  = element_text(angle=90, vjust=0.5, size=8) ) +
  facet_grid(seasonGG ~ riverOrderedGG)


ggsave('figures/grByYearYOY2.png')


```

